### ISSUE TITLE
S3: As an unregistered user, I want to be able to log in as a guest, so I can play the game without needing to create an account first.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#1]
- [x] From the home screen, a user can click a button “play as guest”, upon which he is granted a temporary account 
- [x] This account has limited features, and is only useful for playing. 
- [x] All tests for this feature need to be written and pass.

Task List (front & back):
- [x] sopra-fs24-group-43/client#39
- [x] sopra-fs24-group-43/client#40
- [x] sopra-fs24-group-43/client#41
- [x] sopra-fs24-group-43/client#42
- [x] sopra-fs24-group-43/client#43

- [x] #103
- [x] #104
- [x] #105
- [x] #106

**Comment by FloMatt12** [comment]
5801ca73f2a93d880a8a5cb916f806fbc56364f3
