### ISSUE TITLE
S13: I want to be able to create a new game lobby or join a already existing game lobby. These two options should be separate and easily understood.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#13]
- [x] The user can click on just one button to create a game. There is a separate button to join a already existing game.

Task List (front & back):
- [x] sopra-fs24-group-43/client#116
- [x] sopra-fs24-group-43/client#117
- [x] sopra-fs24-group-43/client#118
- [x] sopra-fs24-group-43/client#119
- [x] sopra-fs24-group-43/client#29
- [x] sopra-fs24-group-43/client#30
- [x] sopra-fs24-group-43/client#31
- [x] sopra-fs24-group-43/client#222
- [x] sopra-fs24-group-43/server#137
- [x] sopra-fs24-group-43/server#140
- [x] sopra-fs24-group-43/server#141

- [x] sopra-fs24-group-43/server#99
- [x] sopra-fs24-group-43/server#100
- [x] sopra-fs24-group-43/server#101
- [x] #161
