### ISSUE TITLE
S14: I want to be able to change some settings about the game when I create a game lobby. These range from the amount of time the drawer has to draw a word, how many rounds of drawing there will be, selecting a certain type of word pool (e.g. only nouns, verbs), how many players can enter the game lobby(the changed settings should be visible to all players in the lobby).

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#14]
- [x] When clicking on the create game putting, i have the option to inspect the game settings and to change them.
- [x] Each setting can be changed independently or can be chosen to not be changed.
- [x] The changes are automatically saved and dont need to be confirmed.
- [x] #155

Task List (front & back):
- [x] sopra-fs24-group-43/client#133
- [x] sopra-fs24-group-43/client#134
- [x] sopra-fs24-group-43/client#25
- [x] sopra-fs24-group-43/client#26
- [x] sopra-fs24-group-43/client#27
- [x] sopra-fs24-group-43/client#28
- [x] sopra-fs24-group-43/client#78
- [x] sopra-fs24-group-43/client#97
- [x] sopra-fs24-group-43/client#98
- [x] sopra-fs24-group-43/client#99
- [x] sopra-fs24-group-43/client#113
- [x] sopra-fs24-group-43/client#114

- [x] sopra-fs24-group-43/server#97
- [x] sopra-fs24-group-43/server#98
- [x] sopra-fs24-group-43/server#130
- [x] sopra-fs24-group-43/server#132
- [x] sopra-fs24-group-43/server#142
