### ISSUE TITLE
S16: As a player, I want to be able to draw freely and see my drawing continuously as I create it on the drawing field, as well as other players in a lobby.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#16]
- [ ] The drawing tool allows players to draw lines and shapes freely on the canvas.
- [ ] The drawing is updated and visible to all players in real-time as it is created.

Task List (front & back):
- [ ] sopra-fs24-group-43/client#22
- [ ] sopra-fs24-group-43/client#23
- [ ] sopra-fs24-group-43/client#24
- [ ] sopra-fs24-group-43/client#75
- [ ] sopra-fs24-group-43/client#76
- [x] sopra-fs24-group-43/client#77
- [x] sopra-fs24-group-43/client#87
- [ ] sopra-fs24-group-43/client#88

- [ ] #95
- [ ] #96

**Comment by simonkli** [comment]
7385231

**Comment by simonkli** [comment]
7385231
