### ISSUE TITLE
S18: As a player, I want to view a leaderboard that showcases the scores accumulated over multiple rounds.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#18]
- [x] A leaderboard is visible to all players during gameplay.
- [x] The leaderboard displays the scores of all participants, updating in real-time after each round.
- [x] #143
- [x] #144
- [x] #145

Task List (front & back):
- [x] sopra-fs24-group-43/client#17
- [x] sopra-fs24-group-43/client#18
- [x] sopra-fs24-group-43/client#19
- [x] sopra-fs24-group-43/server#134
- [x] sopra-fs24-group-43/server#136

- [x] #91

**Comment by RobinStirnimann** [comment]
improved in https://github.com/sopra-fs24-group-43/server/commit/03db24bf5a14cd225eb1cc33ef2007f0565ce5d3
