### ISSUE TITLE
S1: As an unregistered user, I want to create an account using my chosen credentials in order to access features that are only available to registered users.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#2]
- [x] Upon successful registration, the user is automatically logged in and redirected to the home page.
- [x] Upon failure an error is displayed and the user is redirected to the register page. A register error can be that a user name is already taken.
- [x] Logged-in users can log out and log back into their registered profile.

Task List (front & back):
- [x] sopra-fs24-group-43/client#1
- [x] sopra-fs24-group-43/client#2
- [x] sopra-fs24-group-43/client#3
- [x] sopra-fs24-group-43/client#4
- [x] sopra-fs24-group-43/client#5
- [x] sopra-fs24-group-43/client#53
- [x] sopra-fs24-group-43/client#52
- [x] sopra-fs24-group-43/client#56
- [x] sopra-fs24-group-43/client#57
- [x] sopra-fs24-group-43/client#58
- [x] sopra-fs24-group-43/client#59
- [x] sopra-fs24-group-43/client#60
- [x] sopra-fs24-group-43/client#63
- [x] sopra-fs24-group-43/client#64
- [x] sopra-fs24-group-43/client#74
- [x] sopra-fs24-group-43/client#125

- [x] sopra-fs24-group-43/server#35
- [x] sopra-fs24-group-43/server#36
- [x] sopra-fs24-group-43/server#37
