### ISSUE TITLE
S21: As a player, I want to be able to type in my guesses in a chat and also see other guesses in order to play the game.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#21]
- [ ] If a guess is very close but not entirely correct, players receive visual and/or auditory feedback indicating the closeness.

Task List (front & back):
- [x] sopra-fs24-group-43/client#90
- [x] sopra-fs24-group-43/client#91
- [x] sopra-fs24-group-43/client#92
- [x] sopra-fs24-group-43/client#106
- [x] sopra-fs24-group-43/client#140
- [x] sopra-fs24-group-43/client#141
- [x] sopra-fs24-group-43/client#143
- [x] sopra-fs24-group-43/client#144
- [x] sopra-fs24-group-43/server#169
- [x] sopra-fs24-group-43/server#170
- [x] sopra-fs24-group-43/server#171
- [x] sopra-fs24-group-43/server#172
