### ISSUE TITLE
S22: As a player, I want to have drawing tools such as "fill out" "eraser", "draw color change", and "thickness adjustment" to enhance my drawing experience.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#22]
- [ ] The drawing tools include an eraser for precise corrections.
- [ ] Players can change the color of their drawing.
- [ ] The thickness of the drawing tool is adjustable.

Task List (front & back):

- [x] sopra-fs24-group-43/client#11 //integrated in different way
- [x] sopra-fs24-group-43/client#12 //integrated in different way
- [x] sopra-fs24-group-43/client#77
- [x] sopra-fs24-group-43/client#79
- [x] sopra-fs24-group-43/client#80
- [x] sopra-fs24-group-43/client#81
- [x] sopra-fs24-group-43/client#82
- [x] sopra-fs24-group-43/client#83
- [x] sopra-fs24-group-43/client#84
- [x] sopra-fs24-group-43/client#89
- [x] sopra-fs24-group-43/client#100
- [x] sopra-fs24-group-43/client#101
- [x] sopra-fs24-group-43/client#102
- [x] sopra-fs24-group-43/client#103
- [x] sopra-fs24-group-43/client#104
- [x] sopra-fs24-group-43/client#105
- [x] sopra-fs24-group-43/client#107
- [x] sopra-fs24-group-43/client#108
- [x] sopra-fs24-group-43/client#109
- [x] sopra-fs24-group-43/client#110
- [x] sopra-fs24-group-43/client#111
- [x] sopra-fs24-group-43/client#112
- [x] sopra-fs24-group-43/client#127
- [x] sopra-fs24-group-43/client#128
- [x] sopra-fs24-group-43/client#129
- [x] sopra-fs24-group-43/client#130
- [x] sopra-fs24-group-43/client#191

- [x] #88
