### ISSUE TITLE
S23: As a guesser, I want to get points for guessing a word correctly and I want to get a varying amount of points based on the quickness of my guess. 

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#23]
- [x] The guesser gets a visual indication that he got points for a correct answer and how many he got. 
- [x] The points get collected during the rounds for each player and each player can see how many points he has collected over the previous rounds.

Task List (front & back):

- [x] sopra-fs24-group-43/client#10
- [x] sopra-fs24-group-43/client#148
- [x] sopra-fs24-group-43/client#151
- [x] sopra-fs24-group-43/client#152
- [x] sopra-fs24-group-43/client#159
- [x] sopra-fs24-group-43/client#160

- [x] #86
- [x] #87
- [x] sopra-fs24-group-43/server#133
