### ISSUE TITLE
S26: Players want the option to play their own private game. If there are multiple groups of players, each group should have the ability to play their own game (independent from the other group).

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#26]
- [x] For this, the web page needs to support multiple games of many players at the same time.
- [x] The games can’t interfere with each other and only one game can be played per open page.
- [x] Players should have the ability to rejoin their game if they disconnected and reconnected again. They can also decide to not rejoin and play something else.

Task List (front & back):
- [x] sopra-fs24-group-43/client#9
- [x] sopra-fs24-group-43/client#164

- [x] sopra-fs24-group-43/server#83
- [x] sopra-fs24-group-43/server#180
- [x] sopra-fs24-group-43/server#181
- [x] sopra-fs24-group-43/client#206
- [x] sopra-fs24-group-43/server#183
