### ISSUE TITLE
S27: As a player, I should have the ability to stay in a post-game lobby after the game ended, to look at the performance of other players. This would be in the form of a leaderboard and a podium position for the best three players.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#27]
- [x] The end of a game should automatically trigger a post-game lobby which will close after a few minutes.
- [x] The leaderboard needs to display the points of every player fully and correctly and in a way that brings joy to the players.
- [x] The podium positions need to be awarded correctly and display with a style that brings joy to the players.
- [x] The drawings with the name of the drawer are displayed as the background of the view and the players can switch between them.

Task List (front & back):
- [x] sopra-fs24-group-43/client#6
- [x] sopra-fs24-group-43/client#7
- [x] sopra-fs24-group-43/client#8

- [x] sopra-fs24-group-43/server#41
