### ISSUE TITLE
S29: As a player, I want to have a all time leaderboard on the home page.  The ranking should be determined by the individual level of all the users. 

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#29]
-The leaderboard shows the top users in a organized fashion.
-The leaderboard gets updated after each game.

Task List (front & back):
- [x] sopra-fs24-group-43/client#68
- [x] sopra-fs24-group-43/client#192
- [x] sopra-fs24-group-43/client#198
- [x] create navigation from icon to leaderboard page (front)
- [x] display all the top users according to their level (front)
- [x] sopra-fs24-group-43/client#203
- [x] sopra-fs24-group-43/client#204
