### ISSUE TITLE
S2: As a user that has an account, I want to be able to log into my account using my username and password so I can access my profile and the features for registered users.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#3]
- [x] Using only my username and password, a user can log in to his created account.
- [x] Upon success, the user is redirected to the home page.
- [x] Upon failure, the user is redirected to the login page.
- [x] #116
- [x] #117

Task List (front & back):
- [x] sopra-fs24-group-43/client#44
- [x] sopra-fs24-group-43/client#45
- [x] sopra-fs24-group-43/client#46
- [x] sopra-fs24-group-43/client#47
- [x] sopra-fs24-group-43/client#48
- [x] sopra-fs24-group-43/client#228

- [x] #107

**Comment by RobinStirnimann** [comment]
improved in https://github.com/sopra-fs24-group-43/server/commit/03db24bf5a14cd225eb1cc33ef2007f0565ce5d3
