### ISSUE TITLE
S4: As a logged in user, I want to be able to view my user profile

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#4]
- [x] sopra-fs24-group-43/client#50
- [x] sopra-fs24-group-43/client#65
- [x] sopra-fs24-group-43/client#180
- [x] sopra-fs24-group-43/client#190
- [x] sopra-fs24-group-43/client#226
- [x] sopra-fs24-group-43/client#227
- [x] #118

Task List (front & back):
- [ ] implement navigation (not when in-game) when clicking the profile icon to the profile page (front)
- [ ] get user data from Data base using REST request (front)
- [ ] display this data in a pleasing manner (front)
- [ ] provide navigation back to other pages where user was previously (front)
- [ ] implement REST method that provides the necessary data

**Comment by RobinStirnimann** [comment]
improved in https://github.com/sopra-fs24-group-43/server/commit/03db24bf5a14cd225eb1cc33ef2007f0565ce5d3
