### ISSUE TITLE
S6: As a logged in user, I want to be able to add another user to my friends list, so that I can easily find their profile when I want to view it or play with them.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#6]
- [x] whenever a user sees another user he can click on the others name and a pop up 
- [x]  A user can add an existing user to their friends list using their username
- [x] Upon success, that user is then viewable from that users friends list
- [x] #121
- [x] #123
- [x] #122

Task List (front & back):
- [x] sopra-fs24-group-43/client#67
- [x] sopra-fs24-group-43/client#185
- [x] sopra-fs24-group-43/client#212
- [x] sopra-fs24-group-43/client#213
- [x] sopra-fs24-group-43/client#214
- [x] make every name  of users in the app clickable and make a button appear to friend request them (front)
- [x] provide possibility to store open friend requests until the user logs in or send a request directly
