### ISSUE TITLE
S9: As a user I want to change settings such as hotkeys, brightness, dark mode, sound volume,, language, sounds.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#9]
- [x] I can adjust birghtness, dark mode, sound volume in a setting page.
- [x] Changes are applied immediately.
- [x] The changes need to be persistent across user sessions.
- [x] #206
- [x] #205

Task List (front & back):
- [x] sopra-fs24-group-43/client#66
- [x] sopra-fs24-group-43/client#124
- [x] sopra-fs24-group-43/client#132
- [x] sopra-fs24-group-43/client#137
- [x] sopra-fs24-group-43/client#138
- [x] sopra-fs24-group-43/client#171
- [x] sopra-fs24-group-43/client#175
- [x] sopra-fs24-group-43/client#178
- [x] sopra-fs24-group-43/client#184
- [x] add fields to the profile page to change these three options (front)
- [x] store them in the user entity (front)
- [x] update the user entity and REST methods to support these options
